name: Build and Push Docker Image to Repository

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

jobs:
    build-and-push:
        name: Build Image and Push to Repository
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build Docker image
              run: |
                  docker build -t olumayor99/dcind:latest .

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image
              run: |
                  docker push olumayor99/dcind:latest
